{
 "title": "Pipeline Health",
 "tags": [ "internal-monitoring" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "alloc{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Data Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(codec_decoded_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Output Sections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cfgoutputs{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Input Sections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cfginputs{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns", "label": "uptime" }
   ],
   "targets": [
    {
     "expr": "uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU seconds per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "uptime" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Data Channel Occupancy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "chanoccupancy{instance=\"$instance\"} "
    }
   ]
  },
  {
   "title": "Decoded Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "rate(codec_decoded_msgs{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Decoded Messages Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(codec_decoded_bytes{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Base Path Groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "msgs/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(codec_base_path_groups{instance=\"$instance\"}[30s])) by (base_path)"
    }
   ]
  },
  {
   "title": "Decode/Metric Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "decode errors" }
   ],
   "targets": [
    {
     "expr": "codec_base_path_decode_error{instance=\"$instance\"}",
     "legendFormat": "{{base_path}} - {{source}} - {{errortype}}"
    },
    {
     "expr": "metrics_base_path_error{instance=\"$instance\"}",
     "legendFormat": "{{base_path}} - {{section}}/{{source}} - {{errortype}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes", "label": "allocated" }
   ],
   "targets": [
    {
     "expr": "alloc{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "goroutines{instance=\"$instance\"}"
    }
   ]
  }
 ]
}