{
 "title": "Server Monitoring",
 "tags": [ "internal-monitoring" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_cpu]] usage, [[tag_host]]",
     "groupBy": [
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT \"usage_system\" FROM \"cpu\" WHERE (\"host\" = 'devbox') AND $timeFilter GROUP BY \"cpu\"",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hard Drive Free space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] free, [[tag_host]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Blocked Processes, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Running Processes, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "running" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Stopped Processes, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "stopped" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Dead Processes, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "dead" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total Processes, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load 1 min, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Load 5 min, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Load 15 min, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT \"total\" FROM \"processes\" WHERE \"host\" = 'devbox' AND $timeFilter",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available DRAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Available DRAM, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Cached info, [[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}