{
 "title": "Influx-SNMP",
 "tags": [
  "SNMP",
  "demo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU 1 min load",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "CPU 1 min load",
     "measurement": "cpu-router",
     "select": [
      [
       { "params": [ "cpmCPUTotal1minRev" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "PhysicalIndex", "operator": "=", "value": "13" }
     ]
    }
   ]
  },
  {
   "title": "CPU load historical overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU 1 min",
     "measurement": "cpu-router",
     "select": [
      [
       { "params": [ "cpmCPUTotal1minRev" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "PhysicalIndex", "operator": "=", "value": "13" }
     ]
    },
    {
     "alias": "CPU 5 min",
     "measurement": "cpu-router",
     "select": [
      [
       { "params": [ "cpmCPUTotal5minRev" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "PhysicalIndex", "operator": "=", "value": "13" }
     ]
    }
   ]
  },
  { "title": "Memory information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory information (Used)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Used Mem",
     "groupBy": [
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "cempMemPoolHCUsed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "PoolName", "operator": "=", "value": "processor" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "13.1" }
     ]
    }
   ]
  },
  {
   "title": "Memory information (free)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Free Mem",
     "groupBy": [
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "cempMemPoolHCFree" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "PoolName", "operator": "=", "value": "processor" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "13.1" }
     ]
    }
   ]
  },
  { "title": "Interfaces rate information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Interface RX rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName RX",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " *8/2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" }
     ]
    }
   ]
  },
  { "title": "Inventory information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Inventory information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "Name",
     "measurement": "inventory",
     "select": [
      [
       { "params": [ "entPhysicalName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" }
     ]
    },
    {
     "alias": "Serial Number",
     "measurement": "inventory",
     "select": [
      [
       { "params": [ "entPhysicalSerialNum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" }
     ]
    },
    {
     "alias": "Description",
     "measurement": "inventory",
     "select": [
      [
       { "params": [ "entPhysicalDescr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" }
     ]
    }
   ]
  },
  { "title": "BGP information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "BGP Accepted/Advertised prefixes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "Prefixes Accepted (172.16.0.1)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixAccepted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "172.16.0.1" }
     ]
    },
    {
     "alias": "Prefixes Accepted (199.0.0.100)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixAccepted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "199.0.0.100" }
     ]
    },
    {
     "alias": "Prefixes Advertised (172.16.0.1)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixAdvertised" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "172.16.0.1" }
     ]
    },
    {
     "alias": "Prefixes Advertised (199.0.0.100)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixAdvertised" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "199.0.0.100" }
     ]
    }
   ]
  },
  {
   "title": "BGP Denied/Withdrawn prefixes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "Prefixes denied (172.16.0.1)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixDenied" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "172.16.0.1" }
     ]
    },
    {
     "alias": "Prefixes denied (199.0.0.100)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixDenied" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "199.0.0.100" }
     ]
    },
    {
     "alias": "Prefixes withdrawn (172.16.0.1)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixWithdrawn" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "172.16.0.1" }
     ]
    },
    {
     "alias": "Prefixes withdrawn (199.0.0.100)",
     "measurement": "BGP-peer",
     "select": [
      [
       { "params": [ "cbgpPeerPrefixWithdrawn" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "index", "operator": "=", "value": "199.0.0.100" }
     ]
    }
   ]
  },
  { "title": "MPLS information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "All MPLS tunnels",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "alias": "Tunnel name",
     "measurement": "MPLS-total",
     "select": [
      [
       { "params": [ "mplsTunnelName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "index", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "All MPLS tunnels",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "alias": "Tunnel Status",
     "measurement": "MPLS-total",
     "select": [
      [
       { "params": [ "mplsTunnelOperStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "index", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Tunnel Name",
     "measurement": "MPLS-total",
     "select": [
      [
       { "params": [ "mplsTunnelName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "index", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "All MPLS tunnels",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "alias": "Tunnel Uptime",
     "measurement": "MPLS-total",
     "select": [
      [
       { "params": [ "mplsTunnelTotalUpTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.30.110.42" },
      { "condition": "AND", "key": "index", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  }
 ]
}